# Generated by Django 3.2 on 2021-09-13 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('course_registration', '0002_auto_20210912_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='register_subjects', to='courses.course'),
        ),
        migrations.AlterModelTable(
            name='courseregistration',
            table='register_subjects',
        ),
    ]
